# Generated by Django 4.1 on 2022-08-25 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.DecimalField(decimal_places=3, max_digits=8)),
                ('under_50', models.DecimalField(decimal_places=3, max_digits=6)),
                ('over_50', models.DecimalField(decimal_places=3, max_digits=6)),
                ('bonus', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CostSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.DecimalField(decimal_places=3, max_digits=8)),
                ('under_50', models.DecimalField(decimal_places=3, max_digits=6)),
                ('over_50', models.DecimalField(decimal_places=3, max_digits=6)),
                ('bonus', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('cnpj', models.CharField(max_length=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('distance', models.DecimalField(decimal_places=3, max_digits=8)),
                ('code', models.CharField(max_length=10)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='milk.farmer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MilkDeliveries',
            fields=[
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='milk.farm')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
